name: test midthickness surface generation and curvature resampling

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - deepRetinotopy.sh
      - ./main/1_native2fsaverage.sh


  pull_request:
    branches: [ master ]
    paths:
      - deepRetinotopy.sh
      - ./main/1_native2fsaverage.sh
      
jobs:
  test_module1:
    runs-on: "cirun-nectar-large--${{ github.run_id }}"

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Set up neurocommand
      run: /bin/bash tests/test_cvmfs.sh
    - name: test module 1
      env:
        OSF_TOKEN_: ${{ secrets.OSF_KEY }}
        OSF_USERNAME_: ${{ secrets.OSF_USERNAME }}
      run: |
        /bin/bash tests/test_module1.sh