name: test midthickness surface generation and curvature resampling

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - deepRetinotopy.sh
      - ./main/1_native2fsaverage.sh


  pull_request:
    branches: [ master ]
    paths:
      - deepRetinotopy.sh
      - ./main/1_native2fsaverage.sh
      
jobs:
  test_module1:
    runs-on: "cirun-nectar-large--${{ github.run_id }}"
    container: 
      image: vnmd/deepretinotopy_1.0.1
      volumes:
        - ./:./
    steps:
    - uses: actions/checkout@v3
    - name: test module 1
      env:
        OSF_TOKEN_: ${{ secrets.OSF_KEY }}
        OSF_USERNAME_: ${{ secrets.OSF_USERNAME }}
      run: |
        /bin/bash tests/test_module1.sh