name: test deepRetinotopy pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - deepRetinotopy
      - tests/test_cvmfs.sh
      - tests/test_deepRetinotopy.sh
      - .github/workflows/test_deepRetinotopy.yml


  pull_request:
    branches: [ main ]
    paths:
      - deepRetinotopy
      - tests/test_cvmfs.sh
      - tests/test_deepRetinotopy.sh
      - .github/workflows/test_deepRetinotopy.yml
      
jobs:
  test_deepRetinotopy:
    runs-on: "self-hosted"

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Set up neurocommand
      env:
        OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
        OSF_USERNAME: ${{ secrets.OSF_USERNAME }}
        OSF_PROJECT_ID: ${{ secrets.OSF_PROJECT_ID }}
      run: |
        /usr/bin/bash tests/test_deepRetinotopy.sh