name: test resampling

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - deepRetinotopy.sh
      - main/3_fsaverage2native.sh
      - tests/test_cvmfs.sh
      - tests/test_module3.sh
      - .github/workflows/test_module3.yml


  pull_request:
    branches: [ main ]
    paths:
      - deepRetinotopy.sh
      - main/3_fsaverage2native.sh
      - tests/test_cvmfs.sh
      - tests/test_module3.sh
      - .github/workflows/test_module3.yml
      
jobs:
  test_module3:
    runs-on: "cirun-nectar-large--${{ github.run_id }}"

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Set up neurocommand
      env:
        OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
        OSF_USERNAME: ${{ secrets.OSF_USERNAME }}
        OSF_PROJECT_ID: ${{ secrets.OSF_PROJECT_ID }}
      run: /bin/bash tests/test_cvmfs.sh
    - name: test module 3
      run: |
        /bin/bash tests/test_module3.sh
