name: test sign map generation

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - deepRetinotopy
      - signMaps
      - main/2_inference.py
      - main/4_signmaps.py
      - tests/common_setup.sh
      - tests/test_signmaps.sh
      - .github/workflows/test_signmaps.yml


  pull_request:
    branches: [ main ]
    paths:
      - deepRetinotopy
      - signMaps
      - main/2_inference.py
      - main/4_signmaps.py
      - tests/common_setup.sh
      - tests/test_signmaps.sh
      - .github/workflows/test_signmaps.yml
      
jobs:
  test_signMapsGeneration:
    runs-on: "self-hosted"

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Set up neurocommand
      env:
        OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
        OSF_USERNAME: ${{ secrets.OSF_USERNAME }}
        OSF_PROJECT_ID: ${{ secrets.OSF_PROJECT_ID }}
      run: |
        /usr/bin/bash tests/test_signmaps.sh