name: test midthickness surface generation and curvature resampling

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - deepRetinotopy
      - main/1_native2fsaverage.sh
      - tests/common_setup.sh
      - tests/test_module1.sh
      - .github/workflows/test_module1.yml


  pull_request:
    branches: [ main ]
    paths:
      - deepRetinotopy
      - main/1_native2fsaverage.sh
      - tests/common_setup.sh
      - tests/test_module1.sh
      - .github/workflows/test_module1.yml
      
jobs:
  test_module1:
    runs-on: "self-hosted"

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Set up neurocommand
      env:
        OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
        OSF_USERNAME: ${{ secrets.OSF_USERNAME }}
        OSF_PROJECT_ID: ${{ secrets.OSF_PROJECT_ID }}
      run: |
        /usr/bin/bash tests/test_module1.sh
